/**
 * Phase 1 Automation Empire - Gemini Daily Digest Generator
 * 
 * This Apps Script generates intelligent daily summaries of automation activity
 * using Google's Gemini API and commits them to the GitHub repository.
 * 
 * Scheduled to run daily at 23:30 UTC via Apps Script time-based trigger.
 */

/**
 * Main function to generate and commit daily digest
 * Can be triggered manually or via time-based trigger
 */
function generateDailyDigest(date) {
  try {
    const targetDate = date || new Date();
    
    // Get day's automation activity
    const activityData = getActivityForDate(targetDate);
    
    // Generate digest using Gemini
    const digest = generateDigestWithGemini(activityData, targetDate);
    
    // Commit to GitHub
    const fileName = formatDigestFileName(targetDate);
    const commitResult = commitDigestToGitHub(digest, fileName);
    
    Logger.log('Daily digest generated and committed: ' + fileName);
    return commitResult;
    
  } catch (error) {
    Logger.log('Error generating daily digest: ' + error.toString());
    throw error;
  }
}

/**
 * Get automation activity data for a specific date
 * @param {Date} date - The target date
 * @return {Array} Array of activity entries
 */
function getActivityForDate(date) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName('Automation Log');
  
  if (!sheet) {
    Logger.log('No Automation Log sheet found');
    return [];
  }
  
  const data = sheet.getDataRange().getValues();
  const headers = data[0];
  const rows = data.slice(1);
  
  // Filter rows for the target date
  const startOfDay = new Date(date);
  startOfDay.setHours(0, 0, 0, 0);
  const endOfDay = new Date(date);
  endOfDay.setHours(23, 59, 59, 999);
  
  const filteredRows = rows.filter(row => {
    const timestamp = new Date(row[0]); // Timestamp is in first column
    return timestamp >= startOfDay && timestamp <= endOfDay;
  });
  
  Logger.log('Found ' + filteredRows.length + ' activities for ' + date.toDateString());
  return filteredRows;
}

/**
 * Generate digest content using Gemini API
 * @param {Array} activityData - Activity data to summarize
 * @param {Date} date - The date for the digest
 * @return {string} Formatted markdown digest
 */
function generateDigestWithGemini(activityData, date) {
  const apiKey = PropertiesService.getScriptProperties().getProperty('GEMINI_API_KEY');
  
  if (!apiKey) {
    Logger.log('Warning: GEMINI_API_KEY not configured, generating basic digest');
    return generateBasicDigest(activityData, date);
  }
  
  try {
    // Prepare context for Gemini
    const activitySummary = activityData.map(row => ({
      timestamp: row[0],
      source: row[1],
      action: row[2],
      status: row[3],
      details: row[4]
    }));
    
    const prompt = `Generate a concise daily automation empire summary for ${date.toDateString()}.

Activity Data:
${JSON.stringify(activitySummary, null, 2)}

Create a markdown report with these sections:
1. **📊 Activity Summary** - Overview of the day's automation events
2. **✅ Success Metrics** - Number and types of successful automations
3. **⚠️ Issues & Resolutions** - Any errors or problems encountered
4. **💡 Insights** - Patterns or optimization opportunities
5. **🎯 Tomorrow's Focus** - Recommendations for improvement

Keep it professional, informative, and actionable. Use emojis sparingly for section headers only.`;

    // Call Gemini API
    const response = UrlFetchApp.fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=' + apiKey, {
      method: 'post',
      contentType: 'application/json',
      payload: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }]
      }),
      muteHttpExceptions: true
    });
    
    const result = JSON.parse(response.getContentText());
    
    if (result.candidates && result.candidates[0] && result.candidates[0].content) {
      const generatedText = result.candidates[0].content.parts[0].text;
      
      // Add header and footer
      return `# 🏛️ Empire Digest - ${formatDateHeader(date)}

*Automated summary generated by Gemini AI*

---

${generatedText}

---

*"Rome wasn't automated in a day, but every day brings us closer to the perfect empire!"* 🏛️

**Generated:** ${new Date().toISOString()}  
**Total Activities:** ${activityData.length}
`;
    } else {
      Logger.log('Unexpected Gemini API response format');
      return generateBasicDigest(activityData, date);
    }
    
  } catch (error) {
    Logger.log('Error calling Gemini API: ' + error.toString());
    return generateBasicDigest(activityData, date);
  }
}

/**
 * Generate a basic digest when Gemini is unavailable
 * @param {Array} activityData - Activity data to summarize
 * @param {Date} date - The date for the digest
 * @return {string} Formatted markdown digest
 */
function generateBasicDigest(activityData, date) {
  const successCount = activityData.filter(row => row[3] === 'success' || row[3] === 'completed').length;
  const errorCount = activityData.filter(row => row[3] === 'error' || row[3] === 'failed').length;
  
  const actionCounts = {};
  activityData.forEach(row => {
    const action = row[2] || 'unknown';
    actionCounts[action] = (actionCounts[action] || 0) + 1;
  });
  
  const topActions = Object.entries(actionCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([action, count]) => `- ${action}: ${count} times`)
    .join('\n');
  
  return `# 🏛️ Empire Digest - ${formatDateHeader(date)}

*Automated summary (basic mode)*

---

## 📊 Activity Summary

Total automation events recorded: **${activityData.length}**

## ✅ Success Metrics

- Successful operations: **${successCount}**
- Failed operations: **${errorCount}**
- Success rate: **${activityData.length > 0 ? Math.round((successCount / activityData.length) * 100) : 0}%**

## 🎯 Top Actions

${topActions || 'No activities recorded'}

## 💡 Notes

${activityData.length === 0 ? 'No automation activity recorded for this day.' : 'Automation empire continues to grow!'}

---

*"All roads lead to automation!"* 🏛️

**Generated:** ${new Date().toISOString()}  
**Total Activities:** ${activityData.length}
`;
}

/**
 * Commit digest to GitHub repository
 * @param {string} content - The digest markdown content
 * @param {string} fileName - The file name (e.g., "2024-10/29-empire-summary.md")
 * @return {Object} GitHub API response
 */
function commitDigestToGitHub(content, fileName) {
  const githubToken = PropertiesService.getScriptProperties().getProperty('GITHUB_TOKEN');
  
  if (!githubToken) {
    throw new Error('GITHUB_TOKEN not configured in Script Properties');
  }
  
  // GitHub repository details (update these to match your repo)
  const owner = 'buantyswami111-ux';
  const repo = 'phase1-automation-empire';
  const branch = 'main';
  const filePath = 'daily-digests/' + fileName;
  
  // Encode content to base64
  const encodedContent = Utilities.base64Encode(content);
  
  // Check if file already exists
  const checkUrl = `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}?ref=${branch}`;
  let sha = null;
  
  try {
    const checkResponse = UrlFetchApp.fetch(checkUrl, {
      method: 'get',
      headers: {
        'Authorization': 'Bearer ' + githubToken,
        'Accept': 'application/vnd.github.v3+json'
      },
      muteHttpExceptions: true
    });
    
    if (checkResponse.getResponseCode() === 200) {
      const existingFile = JSON.parse(checkResponse.getContentText());
      sha = existingFile.sha;
      Logger.log('File exists, will update. SHA: ' + sha);
    }
  } catch (e) {
    Logger.log('File does not exist, will create new');
  }
  
  // Create or update file
  const commitUrl = `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`;
  const commitMessage = `📜 Daily Digest: ${fileName.replace('.md', '')}`;
  
  const payload = {
    message: commitMessage,
    content: encodedContent,
    branch: branch
  };
  
  if (sha) {
    payload.sha = sha;
  }
  
  const response = UrlFetchApp.fetch(commitUrl, {
    method: 'put',
    contentType: 'application/json',
    headers: {
      'Authorization': 'Bearer ' + githubToken,
      'Accept': 'application/vnd.github.v3+json'
    },
    payload: JSON.stringify(payload),
    muteHttpExceptions: true
  });
  
  const result = JSON.parse(response.getContentText());
  
  if (response.getResponseCode() === 200 || response.getResponseCode() === 201) {
    Logger.log('Successfully committed to GitHub: ' + filePath);
    return result;
  } else {
    throw new Error('GitHub API error: ' + response.getContentText());
  }
}

/**
 * Format the digest file name
 * @param {Date} date - The date
 * @return {string} File name in format "YYYY-MM/DD-empire-summary.md"
 */
function formatDigestFileName(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  
  return `${year}-${month}/${day}-empire-summary.md`;
}

/**
 * Format the date header for the digest
 * @param {Date} date - The date
 * @return {string} Formatted date string
 */
function formatDateHeader(date) {
  const options = { year: 'numeric', month: 'long', day: 'numeric' };
  return date.toLocaleDateString('en-US', options);
}

/**
 * Setup daily trigger for digest generation
 * Run this once to create the automated daily trigger
 */
function setupDailyTrigger() {
  // Delete existing triggers for this function
  const triggers = ScriptApp.getProjectTriggers();
  triggers.forEach(trigger => {
    if (trigger.getHandlerFunction() === 'runDailyDigest') {
      ScriptApp.deleteTrigger(trigger);
    }
  });
  
  // Create new daily trigger at 23:30
  ScriptApp.newTrigger('runDailyDigest')
    .timeBased()
    .atHour(23)
    .nearMinute(30)
    .everyDays(1)
    .create();
  
  Logger.log('Daily trigger created successfully');
}

/**
 * Wrapper function for the daily trigger
 */
function runDailyDigest() {
  const yesterday = new Date();
  yesterday.setDate(yesterday.getDate() - 1); // Generate digest for previous day
  generateDailyDigest(yesterday);
}

/**
 * Manual test function
 */
function testDigestGeneration() {
  const testDate = new Date();
  testDate.setDate(testDate.getDate() - 1); // Test with yesterday's date
  
  Logger.log('Testing digest generation for: ' + testDate.toDateString());
  generateDailyDigest(testDate);
}
